name: emacs-lisp-check
on: [pull_request, push]

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                emacs_version:
                    - 24.4
                    - 29.1
        steps:
            - uses: actions/checkout@v3
            - uses: purcell/setup-emacs@master
              with:
                version: ${{ matrix.emacs_version }}
            - uses: leotaku/elisp-check@master
              with:
                file: tsort.el
